steps:
  # shows the list of changed files (for the human)
  - bash: |
      git status --porcelain
    displayName: 'List files changed'

  # asserts that the list of changed files is zero-length (-z)
  - bash: |
      git update-index --assume-unchanged .npmrc .yarn/releases/yarn-1.22.4.js
      test -z "$(git status --porcelain)"
    displayName: 'Check files unchanged'
