steps:
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/drop
      artifactName: drop

  # .npmrc gets modified by the npmAuthenticate task and so
  # lerna fails to publish packages saying there are uncommited changes.
  - bash: |
      git update-index --assume-unchanged .npmrc .yarn/releases/yarn-1.22.4.js packages/spark-bff/dockerfiles/Dockerfile.prod packages/spark-bff/openshift/deployment-config.yml
      yarn lerna publish from-package --yes
    displayName: 'Publish Packages'
